# Generated by Django 5.2.7 on 2025-10-03 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed')], default='pending', max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('location', models.TextField()),
                ('date_lost_found', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.category')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
