# Generated by Django 4.2.25 on 2025-11-10 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('found_report', models.ForeignKey(help_text='The found item report', on_delete=django.db.models.deletion.CASCADE, related_name='found_conversations', to='reports.report')),
                ('found_user', models.ForeignKey(help_text='User who found the item', on_delete=django.db.models.deletion.CASCADE, related_name='found_conversations', to=settings.AUTH_USER_MODEL)),
                ('lost_report', models.ForeignKey(help_text='The lost item report', on_delete=django.db.models.deletion.CASCADE, related_name='lost_conversations', to='reports.report')),
                ('lost_user', models.ForeignKey(help_text='User who lost the item', on_delete=django.db.models.deletion.CASCADE, related_name='lost_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('lost_report', 'found_report')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
