# Generated by Django 4.2.25 on 2025-11-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='found_report',
            field=models.ForeignKey(blank=True, help_text='The found report this conversation is about (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_conversations', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lost_report',
            field=models.ForeignKey(blank=True, help_text='The lost report this conversation is about (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_conversations', to='reports.report'),
        ),
    ]
