# Generated by Django 5.2.7 on 2025-10-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='reports.report')),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='reports.report')),
            ],
        ),
    ]
